[package]
name = "bevy_peacock_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bevy = "0.12.1"
bevy_peacock_style = { path = "../bevy_peacock_style" }
proc-macro2 = "1.0.78"
quote = "1.0.35"
